### PR TITLE
fix enddate

### LINKED ISSUE #450: Clean up end date code - add support for time & timezone
# Steps required to reproduce the problem

1. Be a developer who cares about dates and times
2. Grep the codebase for how `enddate` is used (https://github.com/opencfp/opencfp/search?utf8=%E2%9C%93&q=enddate)
3. Hang head in shame

# Expected Result

* consistently use the enddate config value and ideally manage it in a central place
* support a timezone in enddate
* support a time as well if someone wants to end at 5pm or something

# Actual Result

* in some places the code uses strtotime with 11:59 appended, other places new DateTime objects are created without time
* there is no way to specify a timezone without breaking the code
* no way to specify time without breaking code

### PR DESCRIPTION
**Pull request by heiglandreas**
This PR moves calls from ```strtotime``` to ```DateTime```.

Additionally the configuration entry ```enddate``` can now be used to also add a time when the CfP ends. You should then also adapt the ```date_format``` to include the time. When no time is given in the config-value the current behaviour is used to let the CfP run until 23:59 of the given day. 

> Note: The CFP will still end 59 seconds before midnight!

* [x] replace ```strtotime``` with ```DateTime```

Fixes #450.

### CODE REVIEW

**Comment by heiglandreas** [comment]
I tested it and it looked good but please - someone should give it a second go!

File: classes/Http/Controller/DashboardController.php [hunk 1]
```diff
@@ -35,20 +35,29 @@ public function showSpeakerProfile()
...
+            $currentTime = new \DateTime('@' . $currentTime);
         }
 
-        return false;
+        $enddate = new \DateTime($this->app->config('application.enddate'));
+        if ($enddate->format('H:i:s') == '00:00:00') {
+            $enddate->add(new \DateInterval('PT23H59M'));
+        }
+
+        if ($currentTime > $enddate) {
```
Comment (pmeth-delvia) [inline classes/Http/Controller/DashboardController.php]: how about just
```
return $currentTime <= $enddate;
```

File: classes/Http/Controller/DashboardController.php [hunk 2]
```diff
@@ -35,20 +35,29 @@ public function showSpeakerProfile()
     /**
      * Check to see if the CfP for this app is still open
      *
-     * @param integer $currentTime
+     * @param integer|\DateTimeInterface $currentTime
```
Comment (heiglandreas) [inline classes/Http/Controller/DashboardController.php]: It's a leftover from the current implementation. I wanted to keep that to not break stuff I didn't find. But you're right. I should remove that and actually break the code to find currently unchanged implementations.

File: classes/Http/Controller/DashboardController.php [hunk 3]
```diff
@@ -35,20 +35,29 @@ public function showSpeakerProfile()
...
 
-        if ($currentTime < strtotime($this->app->config('application.enddate') . ' 11:59 PM')) {
-            return true;
+        if (! $currentTime instanceof \DateTimeInterface) {
+            $currentTime = new \DateTime('@' . $currentTime);
         }
 
-        return false;
+        $enddate = new \DateTime($this->app->config('application.enddate'));
+        if ($enddate->format('H:i:s') == '00:00:00') {
```
Comment (heiglandreas) [inline classes/Http/Controller/DashboardController.php]: Yesterday evening I couldn't find a different solution. Perhaps checking the microseconds might be a way… I'd rather not add an ```endtime```-field in the config. That would make parsing more complicated and scatter the same stuff over two config-entries while it can stay in one…

File: classes/Http/Controller/DashboardController.php [hunk 4]
```diff
@@ -35,20 +35,29 @@ public function showSpeakerProfile()
...
+            $enddate->add(new \DateInterval('PT23H59M'));
```
Comment (heiglandreas) [inline classes/Http/Controller/DashboardController.php]: That's right. But as it was the current behavior I didn't want to break it as I couldn't see whether that's a wanted feature or not. If that was a bug all the time it's more than easy to change it here :)

File: classes/Http/Controller/DashboardController.php (hunk 1 above)
Comment (heiglandreas) [inline classes/Http/Controller/DashboardController.php]: Good idea! Makes it much cleaner!

**Comment by heiglandreas** [comment]
Using the CallForProposal-Class sounds good! I'll need to add a second method though that calculates the end-date from the config-value though.

**Comment by chartjes** [comment]
Thanks @heiglandreas
